/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "NS_XMP_META"]
    pub static mut NS_XMP_META: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_RDF"]
    pub static mut NS_RDF: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_EXIF"]
    pub static mut NS_EXIF: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_TIFF"]
    pub static mut NS_TIFF: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_XAP"]
    pub static mut NS_XAP: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_XAP_RIGHTS"]
    pub static mut NS_XAP_RIGHTS: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_DC"]
    pub static mut NS_DC: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_EXIF_AUX"]
    pub static mut NS_EXIF_AUX: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_CRS"]
    pub static mut NS_CRS: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_LIGHTROOM"]
    pub static mut NS_LIGHTROOM: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_PHOTOSHOP"]
    pub static mut NS_PHOTOSHOP: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_CAMERA_RAW_SETTINGS"]
    pub static mut NS_CAMERA_RAW_SETTINGS: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_CAMERA_RAW_SAVED_SETTINGS"]
    pub static mut NS_CAMERA_RAW_SAVED_SETTINGS: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_IPTC4XMP"]
    pub static mut NS_IPTC4XMP: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_TPG"]
    pub static mut NS_TPG: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_DIMENSIONS_TYPE"]
    pub static mut NS_DIMENSIONS_TYPE: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_CC"]
    pub static mut NS_CC: [::std::os::raw::c_char; 0usize];
}
extern "C" {
    #[link_name = "NS_PDF"]
    pub static mut NS_PDF: [::std::os::raw::c_char; 0usize];
}
